content/community/index.html
=> Fix broken links on community page

content/community/index.html
@azaroth42 speaking of this, is there really a "Discussion Group" as well?
=> link to Slack team archive

content/model/vocab/index.html
At least until we start autogenerating this page
=> add subheads to common vocabularies

content/cookbook/index.html
=> Remove link from Getty

content/model/provenance/index.html, content/model/vocab/index.html
Some examples of `role` and `technique` concepts in AAT, plus a stab at improving definitions for both.
FYI `role` needs an example document. I'm still unclear if this is attached to the `production` as a sibling of `technique`
=> Role and Technique definitions and types

content/model/profile/class_analysis.html
=> Update for InfoCarrier, Inscription, Document

extensions/text.py
=> Change ttl link names

content/community/best-practices/vocabularies/index.html
=> swap description, add stock number

content/community/best-practices/vocabularies/index.html, content/cookbook/getty/photoarchive/index.html, content/model/actor/index.html, content/model/assertion/index.html, content/model/base/index.html, content/model/exhibition/index.html, content/model/object/identity/index.html, content/model/profile/class_analysis.html, extensions/text.py
Per Linguistic / Appellation discussion.  Closes #103
=> update to using Name not Appellation

content/_include/prop_key_map.md, content/community/best-practices/vocabularies/index.html, content/example/text/0.ttl, content/model/object/aboutness/index.html, content/model/provenance/production.html, content/ns/v1/linked-art.json, extensions/text.py
Pharos needs the visual item separate from the man made object.  This implements that change.
Closes #59
=> Use Visual Item

content/model/base/index.html, content/model/object/digital/index.html, content/model/provenance/auctions/index.html
=> update to linguistic object everywhere

content/model/object/aboutness/index.html
=> fix aat landscapes ref

content/example/text/0.json, content/example/text/0.ttl, content/example/text/1.json, content/example/text/1.ttl, content/example/text/10.json, content/example/text/10.ttl, content/example/text/13.json, content/example/text/13.ttl, content/example/text/15.json, content/example/text/15.ttl, content/example/text/16.json, content/example/text/16.ttl, content/example/text/18.json, content/example/text/18.ttl, content/example/text/25.json, content/example/text/25.ttl, content/example/text/6.json, content/example/text/6.ttl, content/example/text/8.json, content/example/text/8.ttl, content/example/text/9.json, content/example/text/9.ttl, content/ns/terms/cidoc.xml, content/ns/terms/inverses.xml, content/ns/terms/linkedart.xml, content/ns/terms/linkedart_crm_enhancements.xml, scripts/make_multiplicity_table.py
=> better ontology management

content/model/profile/index.html, content/model/profile/ontologies/meta.yaml
=> Link ontology files.

content/_include/prop_key_map.md, content/cookbook/getty/photoarchive/index.html, content/model/object/identity/index.html, content/model/provenance/auctions.html, extensions/text.py
Use ore:Aggregations instead of Physical Objects
Also update aat prices in Auctions
=> Aggregations

content/model/provenance/production.html, content/ns/v1/cidoc-extension.json, content/ns/v1/linked-art.json
=> 155 technique

content/model/jsonld/index.html
=> Add media type for jsonld

content/model/provenance/production.html
=> Use technique not classified_as

content/community/index.html, content/index.html
=> Link youtube

content/_include/prop_key_map.md, content/community/best-practices/vocabularies/index.html, content/cookbook/getty/photoarchive/index.html, content/model/actor/index.html, content/model/assertion/index.html, content/model/base/index.html, content/model/collection/index.html, content/model/document/index.html, content/model/exhibition/index.html, content/model/jsonld/index.html, content/model/object/aboutness/index.html, content/model/object/digital/index.html, content/model/object/identity/index.html, content/model/object/physical/index.html, content/model/object/provenance/index.html, content/model/object/rights/index.html, content/model/place/index.html, content/model/provenance/acquisition.html, content/model/provenance/auctions.html, content/model/provenance/curation.html, content/model/provenance/index.html, content/model/provenance/legalclaims.html, content/model/provenance/production.html
Update all examples to use `_label` instead of `label`, and update the description in base/
Preview: https://label--linked-art.netlify.com/model/base/ 
Closes:  https://github.com/linked-art/linked.art/issues/201
=> Use _label

content/community/events/2019/2019_outreach.html, content/community/events/2019/outreach_london.html, content/community/events/index.html
Add initial pages for events, and description of October outreach event in London.
Preview: https://add-event--linked-art.netlify.com/community/events/
=> Initial page for outreach workshop

site.yaml
=> Move LOUD up

content/community/best-practices/vocabularies/index.html
=> Fix mermaid vocab

content/model/place/index.html
Lots of updates to Place documentation
=> Place updates

content/model/base/index.html
=> add note about rdf:Class/crm:Type

content/model/digital/index.html, content/model/provenance/production.html, content/ns/v1/linked-art.json
Complete rewrite to bring up to current thinking.
=> Update Production provenance description

content/model/provenance/acquisition.html, content/model/provenance/custody.html, content/model/provenance/index.html, content/model/provenance/rights.html, extensions/text.py
Merge in prov and new to master updates
=> Prov updates 2

content/media/css/style.css, layout/base.j2
By using delegateTarget not target. Also make SVG root node have white background, just in case
=> make fullscreen use mermaid div, not SVG node

content/media/css/style.css, content/model/base/index.html, extensions/text.py, layout/base.j2
Replace syntax highlighter for examples with crom specific toHtml()
=> Highlight lines

content/model/provenance/encounters.html, content/model/provenance/index.html
Add encounters model to provenance event.
=> Describe encounters in provenance

content/model/object/aboutness/index.html
Both basic VI as an important aspect, and that any human made thing can have a VI
=> Improve Visual Item documentation

content/model/object/physical/index.html
=> Add Measurement docs

content/model/object/ownership/index.html, content/model/provenance/custody.html
And links between custody and current_custodian in the object section.
=> Department custody

content/model/provenance/auctions.html
=> More auction details

content/model/provenance/auctions.html, content/model/provenance/promises.html, extensions/text.py
Update promises page to include commissions, for #216.
=> Commissions

content/model/object/production/index.html
Likewise I hope this will also work for issue #386 . And I will hold back for anything else until @azaroth42 is happy with it.
=> Added sampling example in production by removal, issue 386

content/model/object/physical/index.html
Added a section under physical object description for environmental conditions alongside an example for issue #384 .
=> Environmental condition statements - issue 384

content/model/conservation/index.html
This will need further work but I would like to check the basic structure. It should cover issues #383 and #382 .
=> Main conservation activity page

docs/api/1.0/shared/assignment/index.md
=> fix assignment

build.sh, docs/_redirects
=> try to fix redirects

README.md, docs/model/document/index.md
Fix the end of the file to add closing fence
=> fix translation example

docs/api/1.0/endpoint/digital_object/index.md, docs/api/1.0/endpoint/event/index.md, docs/api/1.0/endpoint/group/index.md, docs/api/1.0/endpoint/person/index.md, docs/api/1.0/endpoint/physical_object/index.md, docs/api/1.0/endpoint/provenance_activity/index.md, docs/api/1.0/endpoint/set/index.md, docs/api/1.0/endpoint/textual_work/index.md, docs/api/1.0/endpoint/visual_work/index.md, docs/cookbook/data-sources/index.md, docs/cookbook/ima/ima-turner.json, docs/cookbook/ima/index.md, docs/cookbook/ima/turner.json, docs/cookbook/index.md
=> fix type and timespan links in model documentation

docs/community/projects/linkedartii/index.md, docs/community/projects/linkedartii/questionnaire-background-resources/index.md
required for Linked Art II questionnaire
=> add questionnaire background resources page

docs/community/projects/linkedartii/index.md
- Adding link to the PIA research project
- Adding extended abstract link
=> Add link to PIA project and extended abstract

docs/api/1.0/principles/index.md
=> Add Solve at the right layer

docs/community/index.md
Change editors based on more recent participation and representativity of organisations
=> amend editorial board

docs/api/1.0/endpoint/visual_work/index.md, docs/model/object/aboutness/index.md
=> model for represents_instance_of_type

docs/model/assertion/index.md, docs/model/object/production/index.md
=> NGA dexid example

docs/api/1.0/endpoint/physical_object/index.md, docs/model/object/production/index.md
=> fix example, cardinality

docs/model/exhibition/index.md
=> artist / exhibition without objects

docs/api/1.0/endpoint/set/index.md, docs/model/collection/index.md
=> oops do 419 too

docs/api/1.0/endpoint/group/index.md, docs/api/1.0/endpoint/person/index.md, docs/model/actor/index.md
add participated_in to api for person and group
closes #453
=> participated_in

docs/model/object/physical/index.md
=> model docs for number of parts

docs/model/exhibition/index.md
=> add classification to exhibition set

docs/_headers, docs/model/profile/index.md, docs/model/profile/ontologies/cidoc.rdf, docs/model/profile/ontologies/linkedart_crm_enhancements.rdf
=> update links and headers for ontologies

docs/api/1.0/ecosystem/index.md
=> change alternate to describedby

docs/api/1.0/index.md, docs/community/index.md, docs/index.md, docs/model/index.md
A try for #536. And change wording for the homepage (for the not so recent video from 2020) as well as removing link to the Linked Art YouTube channel.
=> Add editors and licence to the API page, change wording on homepage

docs/model/object/aboutness/index.md
=> add inscription discussion

docs/model/actor/index.md
=> no metatype, second cxn

.gitignore, docs/api/1.0/endpoint/physical_object/index.md, docs/model/object/ownership/index.md, docs/model/provenance/acquisition.md
=> allow changed ownership through

docs/model/digital/index.md
=> update iiif conforms_to/format docs

docs/model/provenance/custody.md, docs/model/vocab/index.md, docs/model/vocab/optional/index.md, docs/model/vocab/recommended/index.md, docs/model/vocab/required/index.md
Add vocabulary requirements to the model, per #186
=> Vocabulary Draft PR

docs/cookbook/index.md, docs/cookbook/mappings/index.md, docs/cookbook/mappings/schema/index.md
=> schema mapping for leeds

docs/api/1.0/endpoint/textual_work/index.md, docs/api/1.0/endpoint/visual_work/index.md, docs/model/document/index.md
=> conceptually_part_of Abstract Work

docs/model/vocab/optional/index.md, docs/model/vocab/recommended/index.md
Adding some acknowledgement of vocabulary biases for optional and recommended vocabularies, as well invitation to help, in line with https://github.com/linked-art/linked.art/issues/659
=> Bias mitigation suggestions - invitations for help on vocabularies

docs/about/index.md, docs/index.md, docs/model/base/index.md, docs/model/index.md, docs/model/intro/index.md, docs/model/object/index.md, docs/model/object/physical/index.md, docs/model/object/production/index.md
=> Proofreading

docs/software/index.md
Fixing broken link. Not sure what the official approved name is for Cromulent now!
=> Update Crom(ulent) links/name

mkdocs.yml
To match with restructured index pages
=> update nav menus
